version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres_:/var/lib/postgresql/data"
      
  scrapper:
    build: .
    depends_on:
      - db
    
